# Generated by Django 3.0.7 on 2020-07-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200724_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='perchaseorder',
            options={'ordering': ('id',)},
        ),
    ]
