# Generated by Django 3.0.7 on 2020-07-24 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200725_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='perchaseorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perchaseorder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
